# Generated by Django 3.0.3 on 2020-02-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('Password', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
