# Generated by Django 3.0.3 on 2020-02-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200206_0208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginForm',
            new_name='Login',
        ),
    ]
